## Objective

At the end of the experiment you will be able to 

* execute linear algebraic functions
* explain difference between numpy arrays and  Python lists

### Introduction to Numpy

NumPy (Numerical Python) is a Python library for scientific computing, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), the performance is very good.

It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.


**How are NumPy arrays different from Python lists?**

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).


Now it is time to work on practicals. Following Are the given Exercise:


#### Exercise 1: Import the numpy package under the name np

In [ ]:
# Your Code Here
import numpy as np

#### Exercise 2: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [ ]:
# Your Code Here
X = np.array([1, 45, 60, 90])
print(np.cos(X))
print(np.sin(X))
print(np.tan(X))

#### Exercise 3: Given an array *X*. Convert angles from radians to degrees.

X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

In [ ]:
# Your Code Here
X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
degree=np.rad2deg(X)
print(degree)


[-180.  -90.   90.  180.]


#### Exercise 4: Given an arrya *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [ ]:
# Your Code Here
X = np.array([-180., -90., 90., 180.])
radians=np.deg2rad(X)
print(radians)

[-3.14159265 -1.57079633  1.57079633  3.14159265]


#### Exercise 5: Given an array *X*. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of *X*, element-wise. 

X = np.array([-1., 0, 1.])

In [ ]:
# Your Code Here
X = np.array([-1., 0, 1.])
print(np.cosh(X))
print(np.sinh(X))
print(np.tanh(X))

[1.54308063 1.         1.54308063]
[-1.17520119  0.          1.17520119]
[-0.76159416  0.          0.76159416]


#### Exercise 6: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [ ]:
# Your Code Here
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])
print(np.round(X))
print(np.ceil(X))
print(np.floor(X))

[  4.   2.  44.  26.  -1. -10.  -7.]
[ 5.  3. 45. 26. -1. -9. -6.]
[  4.   2.  44.  25.  -2. -10.  -7.]


#### Exercise 7: Given an array *X*. Calculate the difference between neighboring elements, element-wise.

X = np.array([11, 13, 23, 45, 77])

In [ ]:
# Your Code Here
X = np.array([11, 13, 23, 45, 77])
for i in range(len(X)-1):
  print(X[i+1]-X[i])


2
10
22
32


#### Exercise 8: Given two arrays *X* and *Y*. Find the cross product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])
print(np.cross(X,Y))

[-3  6 -3]


#### Exercise 9: Given two arrays *X* and *Y*. Find the dot product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])
print(np.dot(X,Y))

32


#### Exercise 10: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])
print(X/Y)

[0.25 0.4  0.5 ]


#### Exercise 11: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])
print(np.power(X,Y))

[  1  32 729]


#### Exercise 12: Given one array *X* and Y = 3. Compute the remainder of X / Y element-wise using remainder and fmod functions.


X = np.array([1, 2, 3])

In [ ]:
# Your Code Here
Y=3
X = np.array([1, 2, 3])
print(X/Y)

[0.33333333 0.66666667 1.        ]


#### Exercise 13:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [ ]:
# Your Code Here
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
for i in range(len(X)):
  if(X[i]<5):
    X[i]=4
  if(X[i]>9):
    X[i]=8
print(X)  

[8 4 8 4 8 8 4 5]


#### Exercise 14: Given an array *X*. Compute the square of *X*, element-wise.

X = np.array([2, 3, 4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([2, 3, 4, 5, 6])
print(np.power(X,2))

[ 4  9 16 25 36]


#### Exercise 15: Given an array *X*. Compute the absolute value of *X*.

X = np.array([[-44, 3], [4, -3]])

In [ ]:
X = np.array([[-44, 3], [4, -3]])
print(np.abs(X))


[[44  3]
 [ 4  3]]


#### Exercise 16: Given an array *X*. Compute an element-wise indication of the sign of *X*, element-wise.

X = np.array([1, 3, 0, -1, -3])

In [ ]:
# Your Code Here
X = np.array([1, 3, 0, -1, -3])

print(np.sign(X))


[ 1  1  0 -1 -1]


#### Exercise 17: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
# Your Code H
print(np.random.rand(3,3))

[[0.46591428 0.31321678 0.11667024]
 [0.60907131 0.58179481 0.47435134]
 [0.17552048 0.49794316 0.3481161 ]]


#### Exercise 18: Given an array *gaussian*. How do you get the number of dimensions of the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(np.shape(gaussian))

(2, 3, 4)


#### Exercise 19: Given an array *gaussian*. How do you get the shape of an array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(np.shape(gaussian))


(2, 3, 4)


#### Exercise 20: Given an array *gaussian*. How do you get the total number of elements in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
print(np.size(gaussian))

24


#### Exercise 21: Given an array *gaussian*. How do you get memory consumed by each item in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
# print(np.size(gaussian)*np.itemsize(gaussian))
print(gaussian.size*gaussian.itemsize)

192


#### Exercise 22: Given an array *twenty*. How do you access first two rows and three columns

twenty = (np.arange(4 * 5)).reshape(4, 5)

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)

print(twenty[0:2,0:3])

[[0 1 2]
 [5 6 7]]


#### Exercise 23: Given an array *twenty*. How do you reverse the order of elements along columns?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
print(twenty)
print(np.flip(twenty))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


#### Exercise 24: Given an array *twenty*. How do you reverse the order of elements along rows?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
print(np.flip(twenty,axis=1))

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


#### Exercise 25: Given an array *twenty*. How do you shuffle the array along axis - 0


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [61]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.random.shuffle(twenty)
twenty
# print(twenty.shuffle_along_axis(0))
# # shuffle_along_axis(a, axis=1)
# # print(np.shuffle(twenty[:]))

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])